2025-02-26 21:08:52,101 INFO: Locating template 'blog/base.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/blog/base.html') [in /home/ops/.local/lib/python3.12/site-packages/flask/debughelpers.py:178]
2025-02-26 21:08:55,277 INFO: 请求: GET http://192.168.72.128:5000/auth/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:08:55,279 INFO: Locating template 'auth/login.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/auth/login.html') [in /home/ops/.local/lib/python3.12/site-packages/flask/debughelpers.py:178]
2025-02-26 21:08:55,355 INFO: 请求: GET http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:08:55,356 WARNING: 页面未找到: http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:109]
2025-02-26 21:08:57,760 INFO: 请求: GET http://192.168.72.128:5000/blog/ [in /data/myblog/app/__init__.py:141]
2025-02-26 21:08:57,791 INFO: 请求: GET http://192.168.72.128:5000/static/css/blog.css [in /data/myblog/app/__init__.py:141]
2025-02-26 21:08:57,809 INFO: 请求: GET http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:08:57,810 WARNING: 页面未找到: http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:109]
2025-02-26 21:08:59,283 INFO: 请求: GET http://192.168.72.128:5000/auth/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:08:59,342 INFO: 请求: GET http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:08:59,343 WARNING: 页面未找到: http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:109]
2025-02-26 21:09:39,218 INFO: 请求: GET http://192.168.72.128:5000/blog/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:09:39,220 INFO: Locating template 'blog/login.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/blog/login.html') [in /home/ops/.local/lib/python3.12/site-packages/flask/debughelpers.py:178]
2025-02-26 21:09:39,274 INFO: 请求: GET http://192.168.72.128:5000/static/css/blog.css [in /data/myblog/app/__init__.py:141]
2025-02-26 21:09:39,294 INFO: 请求: GET http://192.168.72.128:5000/static/images/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:00,085 INFO: 请求: GET http://192.168.72.128:5000/blog/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:00,119 INFO: 请求: GET http://192.168.72.128:5000/static/css/blog.css [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:00,146 INFO: 请求: GET http://192.168.72.128:5000/static/images/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:30,512 INFO: 请求: POST http://192.168.72.128:5000/blog/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:30,627 ERROR: Exception during request: 'User' object has no attribute 'is_admin' [in /data/myblog/app/extensions.py:176]
2025-02-26 21:12:34,966 INFO: 请求: GET http://192.168.72.128:5000/blog/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:35,008 INFO: 请求: GET http://192.168.72.128:5000/static/css/blog.css [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:35,025 INFO: 请求: GET http://192.168.72.128:5000/static/images/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:41,454 INFO: 请求: POST http://192.168.72.128:5000/auth/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:41,592 INFO: 请求: GET http://192.168.72.128:5000/auth/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:41,650 INFO: 请求: GET http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:41,650 WARNING: 页面未找到: http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:109]
2025-02-26 21:12:58,193 INFO: 请求: POST http://192.168.72.128:5000/auth/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:58,348 INFO: 请求: GET http://192.168.72.128:5000/blog/ [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:58,417 INFO: 请求: GET http://192.168.72.128:5000/static/css/blog.css [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:58,439 INFO: 请求: GET http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:12:58,440 WARNING: 页面未找到: http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:109]
2025-02-26 21:13:10,238 INFO: 请求: POST http://192.168.72.128:5000/auth/logout [in /data/myblog/app/__init__.py:141]
2025-02-26 21:13:10,240 INFO: 用户 test 已登出 [in /data/myblog/app/controllers/auth/__init__.py:64]
2025-02-26 21:13:10,262 INFO: 请求: GET http://192.168.72.128:5000/auth/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:13:10,333 INFO: 请求: GET http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:13:10,333 WARNING: 页面未找到: http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:109]
2025-02-26 21:13:15,719 INFO: 请求: POST http://192.168.72.128:5000/blog/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:13:15,856 ERROR: Exception during request: 'User' object has no attribute 'is_admin' [in /data/myblog/app/extensions.py:176]
2025-02-26 21:13:19,845 INFO: 请求: GET http://192.168.72.128:5000/blog/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:13:19,878 INFO: 请求: GET http://192.168.72.128:5000/static/css/blog.css [in /data/myblog/app/__init__.py:141]
2025-02-26 21:13:19,895 INFO: 请求: GET http://192.168.72.128:5000/static/images/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:13:31,965 INFO: MyBlog 启动 [in /data/myblog/app/__init__.py:69]
2025-02-26 21:13:31,965 INFO: 配置模式: development [in /data/myblog/app/__init__.py:70]
2025-02-26 21:13:31,965 INFO: 调试模式: True [in /data/myblog/app/__init__.py:71]
2025-02-26 21:13:31,965 INFO: 日志文件: /data/myblog/logs/myblog.log [in /data/myblog/app/__init__.py:72]
2025-02-26 21:13:31,982 INFO: 扩展初始化完成 [in /data/myblog/app/__init__.py:85]
2025-02-26 21:13:31,982 INFO: 数据库迁移初始化完成 [in /data/myblog/app/__init__.py:89]
2025-02-26 21:13:31,999 INFO: 蓝图注册完成 [in /data/myblog/app/__init__.py:96]
2025-02-26 21:13:31,999 INFO: 过滤器初始化完成 [in /data/myblog/app/__init__.py:115]
2025-02-26 21:13:32,000 INFO: 应用初始化完成 [in /data/myblog/app/__init__.py:166]
2025-02-26 21:13:46,067 INFO: MyBlog 启动 [in /data/myblog/app/__init__.py:69]
2025-02-26 21:13:46,067 INFO: 配置模式: development [in /data/myblog/app/__init__.py:70]
2025-02-26 21:13:46,067 INFO: 调试模式: True [in /data/myblog/app/__init__.py:71]
2025-02-26 21:13:46,067 INFO: 日志文件: /data/myblog/logs/myblog.log [in /data/myblog/app/__init__.py:72]
2025-02-26 21:13:46,086 INFO: 扩展初始化完成 [in /data/myblog/app/__init__.py:85]
2025-02-26 21:13:46,087 INFO: 数据库迁移初始化完成 [in /data/myblog/app/__init__.py:89]
2025-02-26 21:13:46,104 INFO: 蓝图注册完成 [in /data/myblog/app/__init__.py:96]
2025-02-26 21:13:46,105 INFO: 过滤器初始化完成 [in /data/myblog/app/__init__.py:115]
2025-02-26 21:13:46,106 INFO: 应用初始化完成 [in /data/myblog/app/__init__.py:166]
2025-02-26 21:13:47,229 INFO: MyBlog 启动 [in /data/myblog/app/__init__.py:69]
2025-02-26 21:13:47,229 INFO: 配置模式: development [in /data/myblog/app/__init__.py:70]
2025-02-26 21:13:47,230 INFO: 调试模式: True [in /data/myblog/app/__init__.py:71]
2025-02-26 21:13:47,230 INFO: 日志文件: /data/myblog/logs/myblog.log [in /data/myblog/app/__init__.py:72]
2025-02-26 21:13:47,248 INFO: 扩展初始化完成 [in /data/myblog/app/__init__.py:85]
2025-02-26 21:13:47,249 INFO: 数据库迁移初始化完成 [in /data/myblog/app/__init__.py:89]
2025-02-26 21:13:47,266 INFO: 蓝图注册完成 [in /data/myblog/app/__init__.py:96]
2025-02-26 21:13:47,267 INFO: 过滤器初始化完成 [in /data/myblog/app/__init__.py:115]
2025-02-26 21:13:47,267 INFO: 应用初始化完成 [in /data/myblog/app/__init__.py:166]
2025-02-26 21:13:47,883 INFO: MyBlog 启动 [in /data/myblog/app/__init__.py:69]
2025-02-26 21:13:47,884 INFO: 配置模式: development [in /data/myblog/app/__init__.py:70]
2025-02-26 21:13:47,884 INFO: 调试模式: True [in /data/myblog/app/__init__.py:71]
2025-02-26 21:13:47,884 INFO: 日志文件: /data/myblog/logs/myblog.log [in /data/myblog/app/__init__.py:72]
2025-02-26 21:13:47,900 INFO: 扩展初始化完成 [in /data/myblog/app/__init__.py:85]
2025-02-26 21:13:47,900 INFO: 数据库迁移初始化完成 [in /data/myblog/app/__init__.py:89]
2025-02-26 21:13:47,918 INFO: 蓝图注册完成 [in /data/myblog/app/__init__.py:96]
2025-02-26 21:13:47,918 INFO: 过滤器初始化完成 [in /data/myblog/app/__init__.py:115]
2025-02-26 21:13:47,919 INFO: 应用初始化完成 [in /data/myblog/app/__init__.py:166]
2025-02-26 21:14:02,839 INFO: 请求: GET http://192.168.72.128:5000/auth/login [in /data/myblog/app/__init__.py:141]
2025-02-26 21:14:02,841 INFO: Locating template 'auth/login.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/auth/login.html') [in /home/ops/.local/lib/python3.12/site-packages/flask/debughelpers.py:178]
2025-02-26 21:14:02,910 INFO: 请求: GET http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:141]
2025-02-26 21:14:02,911 WARNING: 页面未找到: http://192.168.72.128:5000/favicon.ico [in /data/myblog/app/__init__.py:109]
